name: x_action_cable
version: 0.4.2

environment:
  sdk: '>=2.17.0 <3.0.0'

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  web_socket_channel: ^2.3.0
  logger: ^1.1.0
  collection: ^1.17.1

dev_dependencies:
  test:
